---
- hosts: webservers
  become: yes
  tasks: 
  - include_tasks: myfile.yml
  - name: install webserver
    yum:
      name: httpd
      state: present
    notify: starthttpd

  - name: copy  my index file into webserver
    template:
      src: myindex.j2
      dest: /var/www/html/index.html
    notify: starthttpd

  handlers:
  - name: starthttpd
    service:
      name: httpd
      state: started

    
