---
# tasks file for tom7deployrole



- name: dowload the skrlogin war file into tomcat webapps folder
  get_url:
    url: https://s3-ap-southeast-1.amazonaws.com/skrit4iac/SKRLogin-1.0.war
    dest: /usr/share/tomcat/webapps/
    force_basic_auth: yes
  notify: tomcat7starting

